#!/bin/zsh

javadoc -linkoffline http://docs.oracle.com/javase/8/docs/api/ http://docs.oracle.com/javase/8/docs/api/ -private -d docs/ ./src/info/kgeorgiy/java/advanced/concurrent/*.java ./src/info/kgeorgiy/java/advanced/mapper/*.java ./src/ru/ifmo/ctddev/kacman/mapper/*.java
