#!/bin/zsh

java -cp "libs/WalkTest.jar:libs/hamcrest-core-1.3.jar:libs/junit-4.11.jar:out/production/Homework 1" info.kgeorgiy.java.advanced.walk.Tester RecursiveWalk ru.ifmo.ctddev.kacman.walk.RecursiveWalk $1
